from apps.fw.models.user_model import *
from apps.fw.models.universidad_model import *
from apps.fw.models.facultad_model import *
from apps.fw.models.carrera_model import *
from apps.fw.models.organizacion_model import *
from apps.fw.models.puesto_model import *
from apps.fw.models.actividad_model import *
from apps.fw.models.egreso_model import *
from apps.fw.models.imagen_model import *
