from apps.fw.admin.general_config_admin import *
from apps.fw.admin.user_admin import *
from apps.fw.admin.universidad_admin import *
from apps.fw.admin.facultad_admin import *
from apps.fw.admin.carrera_admin import *
from apps.fw.admin.organizacion_admin import *
from apps.fw.admin.puesto_admin import *
from apps.fw.admin.actividad_admin import *
from apps.fw.admin.egreso_admin import *
from apps.fw.admin.privacidad_admin import *
from apps.fw.admin.imagen_admin import *
from apps.fw.admin.ciudad_admin import *
from apps.fw.admin.email_admin import *
from apps.fw.admin.log_siu_admin import *
