# Generated by Django 4.1 on 2023-04-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fw", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Universidad",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("universidad", models.CharField(max_length=200)),
                ("acronimo", models.CharField(blank=True, max_length=25, null=True)),
                ("domicilio", models.CharField(blank=True, max_length=200, null=True)),
                ("web", models.URLField(blank=True, null=True)),
                (
                    "estado",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la actividad de la universidad esta vigente.Por defecto esta activa",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefono", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Universidad",
                "verbose_name_plural": "Universidades",
                "ordering": ["-universidad"],
            },
        ),
    ]
