# Generated by Django 4.1 on 2023-04-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fw", "0002_universidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facultad",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("facultad", models.CharField(max_length=200)),
                ("acronimo", models.CharField(blank=True, max_length=25, null=True)),
                ("domicilio", models.CharField(blank=True, max_length=200, null=True)),
                ("web", models.URLField(blank=True, null=True)),
                (
                    "estado",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la actividad de la facultad esta vigente. Por defecto esta activa",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefono", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "universidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facultades",
                        to="fw.universidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facultad",
                "verbose_name_plural": "Facultades",
                "ordering": ["facultad", "-universidad"],
            },
        ),
    ]
