# Generated by Django 4.1 on 2023-04-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fw", "0005_titulo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizacion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "organizacion",
                    models.CharField(max_length=200, verbose_name="Organizacion"),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("p", "Pública"),
                            ("e", "Privada"),
                            ("i", "Independiente"),
                        ],
                        help_text="Organizacion pública, privada o trabajo independiente",
                        max_length=200,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "empleados",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1-10 Empleados (FW)"),
                            (2, "11-100 Empleados (FW)"),
                            (3, "101-1000+ Empleados (FW)"),
                            (4, "1 Empleado (LinkedIn)"),
                            (5, "1-10 Empleados (LinkedIn)"),
                            (6, "11-50 Empleados (LinkedIn)"),
                            (7, "51-200 Empleados (LinkedIn)"),
                            (8, "201-500 Empleados (LinkedIn)"),
                            (9, "501-1000 Empleados (LinkedIn)"),
                            (10, "1001-5000 Empleados (LinkedIn)"),
                            (11, "5001-10000 Empleados (LinkedIn)"),
                            (12, "10001+ Empleados (LinkedIn)"),
                        ],
                        null=True,
                        verbose_name="Cantidad de empleados",
                    ),
                ),
                ("estado", models.BooleanField(default=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "web",
                    models.URLField(blank=True, null=True, verbose_name="Sitio Web"),
                ),
            ],
            options={
                "verbose_name": "Organizacion",
                "verbose_name_plural": "Organizaciones",
            },
        ),
    ]
