# Generated by Django 4.1 on 2023-04-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fw", "0006_organizacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Puesto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("puesto", models.CharField(max_length=200)),
                (
                    "descripcion",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Puestos de trabajo",
            },
        ),
    ]
