# Generated by Django 4.1 on 2023-05-01 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fw", "0008_actividad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Egreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ciclo_egreso",
                    models.DateField(
                        blank=False, null=False, verbose_name="Año de Egreso"
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Matricula"
                    ),
                ),
                ("postgrado", models.BooleanField(default=False)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Egreso",
                "verbose_name_plural": "Egresos",
                "db_table": "fw_egresado_carrera",
                "ordering": ["ciclo_egreso"],
            },
        ),
        migrations.AddField(
            model_name="carrera",
            name="egresado",
            field=models.ManyToManyField(
                blank=True,
                related_name="carreras",
                through="fw.Egreso",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="egreso",
            name="carrera",
            field=models.ForeignKey(
                blank=False,
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carreras",
                to="fw.carrera",
            ),
        ),
        migrations.AddField(
            model_name="egreso",
            name="usuario",
            field=models.ForeignKey(
                blank=False,
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="egresos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
