# Generated by Django 4.1 on 2023-05-26 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fw", "0009_egreso_carrera_egresado_egreso_carrera_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "plan",
                    models.CharField(max_length=200, verbose_name="Plan de estudios"),
                ),
                (
                    "acreditacion",
                    models.CharField(
                        max_length=200, verbose_name="Año de acreditación"
                    ),
                ),
                (
                    "acreditadora",
                    models.CharField(
                        default="CONEAU",
                        max_length=200,
                        verbose_name="Organizacion acreditadora",
                    ),
                ),
                (
                    "estado",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la actividad del titulo esta vigente. Por defecto esta activa",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes",
                        to="fw.carrera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Planes",
            },
        ),
    ]
