# Generated by Django 4.1 on 2023-06-23 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fw", "0011_privacidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imagen",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Imagen Perfil",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL Imagen Perfil"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estado",
                    models.BooleanField(
                        default=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen",
                "verbose_name_plural": "Imagenes",
            },
        ),
    ]
