# Generated by Django 4.1 on 2023-07-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fw", "0012_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ciudad",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ciudad", models.CharField(max_length=200)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ciudad",
                "verbose_name_plural": "Ciudades",
            },
        ),
    ]
