# Generated by Django 4.1 on 2023-07-30 00:36
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fw", "0015_alter_fwuser_ciudad_actual_alter_fwuser_ciudad_natal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plantilla", models.CharField(max_length=100)),
                ("asunto", models.CharField(max_length=200)),
                ("cuerpo", ckeditor.fields.RichTextField()),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
    ]
