# Generated by Django 4.1 on 2023-09-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fw", "0016_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciudad",
            name="lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=11,
                null=True,
                verbose_name="Latitud",
            ),
        ),
        migrations.AddField(
            model_name="ciudad",
            name="long",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=11,
                null=True,
                verbose_name="Longitud",
            ),
        ),
    ]
