# Generated by Django 4.1 on 2023-09-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fw", "0017_ciudad_lat_ciudad_long"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogSIU",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField(verbose_name="Cantidad de egresados")),
                (
                    "origen",
                    models.IntegerField(
                        choices=[(1, "AUTO"), (2, "MANUAL")],
                        verbose_name="Actualización",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de SIU",
                "verbose_name_plural": "Log de SIU",
            },
        ),
    ]
